### ISSUE TITLE
Version 3.1.0 does not work with PHP 7.0, but no version constraints given

### ISSUE THREAD

**Issue by DrillSergeant** [Flowpack/Flowpack.Neos.FrontendLogin#27]
I just (tried to) did patchlevel-rollouts to all of our Neos 3.x installations (still quite a few) where this package is installed on most of them.

Our Neos 3.3 installation are hosted on PHP 7.0 machines (which is fine with the version constraints of Neos 3.3).
Because of https://github.com/Flowpack/Flowpack.Neos.FrontendLogin/blob/3.1.0/Classes/Controller/ModuleController.php#L122 (the nullable typehint for  the parameter $expirationDate) is depending on PHP 7.1 the package does not work anymore.

Suggestions for possible solutions:
* Variant A) remove the typehint and use the php 7.0 compatible syntax
```
public function createAction($username, array $password, User $user, \DateTime $expirationDate = null): void
```
* Variant B) Add a version contraint to php >=7.1 for this package
* Variant C) Add a version contraint to neos/neos 4.x for this package

**Comment by kdambekalns** [comment]
Thanks for reporting this, my bad. But… **[PHP 7.0 has been EOL since the beginning of 2019](https://www.php.net/supported-versions.php)** (and out of regular maintenance since the beginning of 2018), so I would go for option B) to be honest.

To actually fix the issue that would mean releasing 3.1.1 and having to remove the 3.1.0 tag. Or move the 3.1.0 tag to the new commit. Because if 3.1.0 is still there, it would be used, just 3.1.0 would be seen as incompatible.

That being said, this seems like a lot of work to mark it as incompatible with a PHP version you should no longer be using at all, anyway. WDYT?

**Comment by mrimann** [comment]
Basically agreed, PHP 7.0 is EOL. And yes, it would be cool to always upgrade and move customer installations to the most current versions of $everything (OS, PHP, Flow/Neos). Sadly, the reality out in the field is a bit more complicated TBH.

Since we're Using Ubuntu LTS as the OS which is still supported, they backport PHP security fixes also to the PHP 7.0.x packages they deliver.

In my opinion, any package that states compatibility with `"neos/neos": ">=3.0 <5.0"` should either
- be compatible with *all* supported PHP versions that these Neos-Versions are marked compatible (Neos 3.3.x > Flow 4.3.x > requires `php: ~7.0` (as of https://packagist.org/packages/neos/flow#4.3.23)
- or have a clear PHP version constraint, that excludes certain PHP versions and makes sure that this package release is not compatible

So, your plan with Option B + (re)moving the tag shall solve our problem and we'd appreciate that a lot!

**Comment by kdambekalns** [comment]
For me the Ubuntu LTS has 7.2: https://packages.ubuntu.com/bionic/php 😜 – but, yeah, they have awfully long LTS cycles, so I assume you are using xenial.

Point taken, the problem is: I could not (yet) find out, how composer behaves in this case:

- someone has 3.1.0 installed and in `composer.lock`
- the tag is removed
- `composer install` is called

Would that break?

**Comment by kdambekalns** [comment]
So, I actually gave this a try, and it does not break. The lock file has the tag, but installs based on the commit hash, so installing still works. The only thing that would break, is requiring the exact version, but that's unlikely.

**Comment by kdambekalns** [comment]
Fixed… 👋

**Comment by DrillSergeant** [comment]
Oh nice, that is great. Thank you so much.

**Comment by mrimann** [comment]
We have both Ubuntu 18.04 Bionic and Ubuntu 16.04 Xenial based servers, so there's not just "the LTS" but a few more options :-)

Thanks @kdambekalns !
